@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUxYmYxYzY2LWExN2MtNDU3ZC05NmY1LTRiN2M4ZjJkYjJmMSIsInVzZXJOYW1lIjoiQWRtaW4xIiwicGFzc3dvcmQiOiIkMmEkMDgkZHNJZmRha29ydktkblpoRkNZYnhuT3ZPenNReXZINXJSay80L1Q5RGt0NzkvRFg4Mi5rd3kiLCJjcmVhdGVkQXQiOiIyMDI1LTAxLTEzVDIwOjUyOjE2LjU3MVoiLCJpYXQiOjE3MzY4MDIxODUsImV4cCI6MTczOTM5NDE4NX0.EqgvUNyCc-sRNUyadvJv_G4R7wmMSU9xPZ-QenCiOfo
###
GET http://localhost:5000/api/v1/seeder/userSeeder
Content-Type: application/json

###
POST  http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{     "userName"    : "Admin1",
       "password" : "Admin123!"
}

###
get  http://localhost:5000/api/v1/userManagementAdmin/getUser
Content-Type: application/json
Authorization: Bearer {{token}}



###
get  http://localhost:5000/api/v1/article/getArticle
Content-Type: application/json
Authorization: Bearer {{token}}


###
get  http://localhost:5000/api/v1/article/getArticleById/e836f29a-126f-11f0-abbc-a841f422e754
Content-Type: application/json
Authorization: Bearer {{token}}


###
get  http://localhost:5000/api/v1/jurnal/getJurnal
Content-Type: application/json
Authorization: Bearer {{token}}


###
get  http://localhost:5000/api/v1/jurnal/getJurnalById/1acf7676-1270-11f0-abbc-a841f422e754
Content-Type: application/json
Authorization: Bearer {{token}}



###
get  http://localhost:5000/api/v1//getMeditasi
Content-Type: application/json
Authorization: Bearer {{token}}


###
get  http://localhost:5000/api/v1/meditasi/getMeditasiById/3e24e97c-1270-11f0-abbc-a841f422e754
Content-Type: application/json
Authorization: Bearer {{token}}





