@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA3MTcwMGQ4LTA1NDUtNDNiYi1iZmJkLTRmYWMxNzY0OWZmNyIsInVzZXJOYW1lIjoiUGFzaWVuMSIsInBhc3N3b3JkIjoiOWZiZjNmZWQyZWFiNzM0YTBlYTVlNmJkMzU2MDQ0NWQ6NDhjNTFjZDcyZjZjY2FiZWIwNmI0OTdiMjlmNTNkNWMiLCJjcmVhdGVkQXQiOiIyMDI1LTA0LTA1VDAxOjU3OjA1LjUxMloiLCJpYXQiOjE3NDM4OTgyOTMsImV4cCI6MTc0Mzg5ODI5NH0.MfhHMzmTJvoCt-vgrtsEgVznT5b6uxWrzP3K0PzR9-Q
###
GET http://localhost:5000/api/v1/seeder/userSeeder
Content-Type: application/json

###
POST  http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{     "userName"    : "Pasien1",
       "password" : "Pasien123!"
}

###
get  http://localhost:5000/api/v1/userManagementAdmin/getUser
Content-Type: application/json
Authorization: Bearer {{token}}



###
get  http://localhost:5000/api/v1/article/getArticle
Content-Type: application/json
Authorization: Bearer {{token}}


###
get  http://localhost:5000/api/v1/article/getArticleById/e836f29a-126f-11f0-abbc-a841f422e754
Content-Type: application/json
Authorization: Bearer {{token}}


###
get  http://localhost:5000/api/v1/jurnal/getJurnal
Content-Type: application/json
Authorization: Bearer {{token}}


###
get  http://localhost:5000/api/v1/jurnal/getJurnalById/1acf7676-1270-11f0-abbc-a841f422e754
Content-Type: application/json
Authorization: Bearer {{token}}



###
get  http://localhost:5000/api/v1//getMeditasi
Content-Type: application/json
Authorization: Bearer {{token}}


###
get  http://localhost:5000/api/v1/meditasi/getMeditasiById/3e24e97c-1270-11f0-abbc-a841f422e754
Content-Type: application/json
Authorization: Bearer {{token}}



###
POST  http://localhost:5000/api/v1/generate-meet/generate-meet-link
Content-Type: application/json

{
   "pasienId": "071700d8-0545-43bb-bfbd-4fac17649ff7",
    "psychologyId": "5e7e66a9-e6e3-4873-88eb-40d295383fcb",
    "appoinmentDate": "2025-07-15T14:30:00Z",
    "durationMinute": 60,
    "meetLink": "https://meet.google.com/abc-defg-hij",
    "topikMasalah": "Stress Kerja",
    "deskripsiMasalah": "Mengalami tekanan berlebih di tempat kerja"
}

###
get  http://localhost:5000/api/v1/generate-meet/getAppoinmentById/7db5c427-126f-11f0-abbc-a841f422e754
Content-Type: application/json
Authorization: Bearer {{token}}

###
get  http://localhost:5000/api/v1/generate-meet/getAppoinment
Authorization: Bearer {{token}}






